local_backend: true

backend:
  name: github
  repo: przystanekpolaris/przystanekpolaris
  branch: master
  base_url: https://decap-proxy.wiatrok35.workers.dev
  auth_endpoint: /auth
  auth_scope: repo

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Strony"
    files:
      - label: "Agenda"
        name: "agenda"
        file: "content/site/agenda.md"
        fields:
          - { label: "Text", name: "body", widget: "markdown" }
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Show header image on post page", name: "showHeaderImage", widget: "boolean", required: false, default: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Text", name: "body", widget: "markdown" }
  - name: "gallery"
    label: "Galeria"
    folder: "content/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - { label: "Order", name: "order", widget: "number", required: false, value_type: "int", min: 0, default: 0 }
